title: The Octopus style guide
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "/OctoStyle" # the subpath of your site, e.g. /blog
url: "https://octopusdeploy.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]

collections:
  terms:
    output: false